### ISSUE TITLE
/entries endpoint - allow filtering by moderation_state

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#124]
Pulse front end currently doesn't have any client side filtering. It fully replies on the API to return the entries it looks for. We should allow filtering by `moderation_state`as it will make [Build moderation front-end](https://github.com/mozilla/network-pulse/issues/541) work a lot easier as well as make the codebase cleaner since we can just rely on the API to filter entries instead of adding client side filtering and modifying how things are set up just for [state dropdown on the moderation page](https://github.com/mozilla/network-pulse/issues/541#issuecomment-307177652) to work.

**Comment by Pomax** [comment]
This has been added to the pulse-api as it exists in the network-api now, so the routes will be:
- `/api/pulse/entries/moderationstates` returns a JSON object with the information on which moderation states exist by name and id
- `/api/pulse/entries/?moderationstate=<name of the state>` explicitly gets only the list of entries of a particular moderation state (with the additional query arguments doing additional filtering inside that set before giving you the response)
- `/api/pulse/entries/<entry id>/moderate/<state id>` lets you (attempt to) toggle the moderation state for a specific entry. This requires passing in the state `id`, not the name. If the calling use has moderation rights, this will succeed, otherwise this should be a 403 forbidden.

**Comment by mmmavis** [comment]
@Pomax cool I'll use those endpoints for now. Could you whitelist `localhost:3000` so I can make request from Pulse's dev env?

**Comment by mmmavis** [comment]
Oops sorry I think it was me who had to whitelist `network-dev.mofostaging.net` on Pulse 😉

**Comment by mmmavis** [comment]
@Pomax 

Sorry I'm horrible. :nauseated_face:  Seems like whitelisting `network-dev.mofostaging.net` on Pulse is not enough. We do need  to whitelist `localhost:3000` on `network-dev.mofostaging.net` as well.

<img width="520" alt="screen shot 2017-06-14 at 5 51 44 pm" src="https://user-images.githubusercontent.com/2896608/27160585-2af01df4-512a-11e7-91fd-3d044a005564.png">

**Comment by Pomax** [comment]
after working on this dedicated for a day and talking with @alanmoo, I'm going to recommend we don't move to network-api, but instead stay with pulse-api -- there is a PR open (https://github.com/mozilla/network-pulse-api/pull/125) that will add all the features needed in this repo instead.

Apologies for that confusion.

**Comment by mmmavis** [comment]
I think this is done, correct? @Pomax

**Comment by Pomax** [comment]
it is, closing.
