### ISSUE TITLE
Expose entry's submitter's name in the /entries endpoint

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse-api#138]
Context: we want to show the person who submitted the entry on Pulse front end (see this [ticket](https://github.com/mozilla/network-pulse/issues/528))

Currently the `/entries` endpoint doesn't expose the "published by" meta. I realized that "published by" currently is set to the submitter's email and not their full name. I think it's best that we do not expose people's emails so exposing the "published by" meta straight is probably not a good idea. @alanmoo @Pomax can you suggest what we can do? I would love to take this ticket on if it's an easy task. But it seems like there might be some object mapping involved and I can't gauge how difficult it's gonna be for this work.

**Comment by alanmoo** [comment]
We have user names because we're using Google Auth, so this should be doable. I think the work would mainly need to happen in the `EntrySerializer`. We'd probably also want to expose the database id of the user, so that we could do lookups around that in the future. @Pomax might be able to give some better pseudo-code to get you started though.

**Comment by Pomax** [comment]
Similar to what we do with bookmark_count, we can introduce a field in the serializer that resolves `published_by` to a name rather than an email. For instance:
```python
    publisher_name = serializers.SerializerMethodField()

    def get_publisher_name(self, instance):
        """
        Get the name of the user who published this entry
        """
        return instance.published_by.name
```
