### ISSUE TITLE
Optimize user image uploads (if we aren't already)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#142]
Users will sometimes upload crazy big images. We should limit on kb and/or resolution if that isn't already in place.

**Comment by Pomax** [comment]
We just added some front end code to Thimble that takes "huge images" and iteratively resizes them until their filesize is around 250KB (+/- 30KB I think).

We could spin that code out of Thimble as a small JavaScript library and add that to the Pulse client so that users simply cannot attach images that are too big, rather than trying to tackle the issue on the API side (given that the only way non-admin users get to interact with Pulse is through the client).

**Comment by xmatthewx** [comment]
That sounds good. Closing this. Tracking in frontend repo: https://github.com/mozilla/network-pulse/issues/591
