### ISSUE TITLE
Setup API for 'Submitter is Creator' feature

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse-api#160]
When User A submits an item, we want to give them a checkbox to identify themselves as one of the creators. If the form knows who they are and has their profile ID, does it send that along with others? Or, does it tell the api to handle it?

Note: in the future, project creators will be linked to Profiles, not Users. 

Frontend form work here: https://github.com/mozilla/network-pulse/issues/573

**Comment by Pomax** [comment]
We can tap into the Entry `post` function, to filter out the boolean that says "poster is creator". The challenge is that this relies on the logged in user, who is logged in by email, having a profile that tells us what their "creator name" is so we can link to that. That means this issue is probably blocked on the profile work.

**Comment by xmatthewx** [comment]
I believe the PR on this is ready to be merged and that this can be closed.
