### ISSUE TITLE
Possibly incorrect myprofile route

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse-api#186]
Currently, to access your profile, you need to hit https://network-pulse-api-staging.herokuapp.com/api/pulse/profiles/myprofile/.

I think we had intended it to be https://network-pulse-api-staging.herokuapp.com/api/pulse/myprofile/ instead.

Feel free to close if the above is not true.

**Comment by Pomax** [comment]
@xmatthewx ?

**Comment by xmatthewx** [comment]
What if we do this:

...org/profiles/ID
...org/profiles/ID/edit

**Comment by Pomax** [comment]
I'd like to avoid an `/edit` tied to a specific id, since I should not be able to look at your profile, add `/edit` at the end, and because of a security exploit in Django suddenly be able to edit your profile. Can I counter suggest:

...org/profiles/id
...org/myprofile
...org/myprofile/edit

where the second url is always your own profile, and only that url allows for an /edit suffix?

**Comment by xmatthewx** [comment]
Ok. That makes sense re: an exploit. Is /myprofile a duplicate of /profiles/myid? Or could /myprofile just be the form to edit?

**Comment by Pomax** [comment]
/myprofile and /profiles/myid would have the same output, but only /myprofile should allow an /edit suffix for security purposes
