### ISSUE TITLE
Make creator search "contains"

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#247]
Let's say I want to mark "Pomax" as the creator of a project. But his profile is `Mike 'Pomax' Kamermans`. Typing in a creator name won't currently show his profile as an option. It should.

**Comment by Pomax** [comment]
Based on some discussion in the chat, the right way to do this is probably two-fold:

- on the API side, do a search for `startswith`, and see if that yields fewer results than fit in a single `page_size` sized result set. If so, redo the search using `contains`.
- on the client, make sure to sort the autocomplete suggestions so that any ordering difference between `startswith` and `contains` at the API are invisible to the user.
