### ISSUE TITLE
Add fellowship identification fields for profiles

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#269]
As part of the work to integrate Pulse profiles onto the foundation site, we need a way to identify fellows. The data points I think we need to add/be able to filter by:

* fellowship type (or "all" for "is a fellow")
* fellowship year

There's other work to be done for actual data on the profiles, but this feels like the way to get started with API work. @xmatthewx @taisdesouzalessa am I missing anything here?

**Comment by taisdesouzalessa** [comment]
We also had interests (decentralization, digital inclusion and so on) - are those already accounted for because they are Pulse categories?

**Comment by xmatthewx** [comment]
All the fields on foundation site profiles, like interests, should be included on Pulse. 

These official fields should be a new model, associated with a profile, not accessible by all users. Staff would create a new `extended-profile` via an existing profile in django. In the future, once a user has an extended profile we could enable them to edit it as part of their regular profile, but that's not necessary for a first release of this. 

Make sense?

**Comment by Pomax** [comment]
Some thoughts on how we can conceptually represent these changes implement this, which will steer the implementation.

Some assumptions (please let me know if any of these are incorrect): 

1. fellows are always users.
2. fellows fill this role for a fixed term (10 months?)
3. there is a low number of fellows each year (e.g. toggling people by us is acceptable and manageable)
4. extended profile data for fellows has parts, or consists entirely of, data that is only relevant to fellows

This leads to a few tasks:

- the system needs a way to set and identify certain users as fellows
- the system needs to be able to search in the set of 'fellows'
- the system needs a way to identify there is extended profile information
- the system needs to be able to search in extended profile information

Right now, we have a design in which a `Profile` is the master authority and if associated with a user, points to a `User` object. Consulting a user's profile information involves following the relationship "Profile -> User" in reverse.

## "being a fellow" options

With fellows added as a specific user subset, we have a few options for the "marking users as fellows" portion of the work:

### Django roles

We can mark specific users as fellows in the same way we mark users as admin/staff/moderator right now. This would be a system-managed value and no explicit code changes would be necessary.

Search would be run on an easily cached-for-a-long-time subset of users, based on their django role as fellow, after which it's identical to user search

### explicit field in the user class

We can add a new field to the user class such as `is_fellow` that can be toggled on/off through the admin interface.

This would require a data migration and would introduce a column to the user table that is unused by the overwhelming majority of users.

### explicit field in the Profile

We can add the fellowship identity as part of a user profile, which keeps the user model clean, and treats "being a fellow" as a kind of meta data. This could be an explicit field, but could also be signaled by the presence of "extended profile data for someone who is a fellow":

Adding an `is_fellow` to the profile would require making sure people can't just set that checkbox themselves when they edit their profile online, but would make the lookup to see if someone is a fellow faster than if we have extended profile information and we set up a link from `Profile` to an `ExtendedProfile` in which we'd have to check the profile type to make sure it was the extended profile associated with a fellow, and not with, say, an organisation or regular user.

## "extended profile" options

There are a few ways to add extended profile information to the system with pros and cons with respect to maintenance, extending with even more data, and speed of search.

### Put it all in `Profile`

This is absolutely the fastest if we don't want to introduce any additional lookups for search to work. We add all the fields we need to the `Profile` class, irrespective of whether this data will only be used for a tiny fraction of all users.

As downside, every time a new user role is added this will grow the `Profile` class, and associated table, with fields that will be used by tiny fractions of the userbase

### Use an `ExtendedProfile` class

We can create an Extended profile class that has a one-to-one relation with a base `Profile` so that data access requires a single additional lookup per Profile. The extended profile contains all the fields for fellows, right now, and if we need more information for different roles, we just add them in here. 

### Use a universal `ExtendedProfile` class + `FellowProfile` class

We can also create an Extended Profile class that only contains universal extended profile information, and can point to a `FellowProfile` (in a one-to-one relation) that houses only the fellow-specific profile information. This introduces an extra step of indirection, but keeps all the information contained in easily maintained, self-contained units.

## the pros and cons

The main aspects we want to think about when choosing what to go with are probably:

- how fast can we implement this
- how easy will it be to maintain/extend
- how fast can we search through how we implemented things
- how much space is used up for fields that aren't used by almost all users of the system, only to accomodate fellows

I'd lean towards using Django roles to mark users as fellows, just because it means no code needs to be written for that particular aspect of this work, and I like the cleanliness of a universal extended profile + fellow-specific profile but I don't know and can't really guess what the search impact would be. 

Thoughts?

(Also, cc @gideonthomas @alanmoo)

**Comment by Pomax** [comment]
Based on https://github.com/mozilla/network-pulse/issues/657 the profile side of things seem to come best match the "Extend `Profile` without additional classes" use-case. The implementation for this is tracked in https://github.com/mozilla/network-pulse-api/issues/271

**Comment by xmatthewx** [comment]
Is this done?

**Comment by gideonthomas** [comment]
Closing as done. Feel free to re-open if I'm wrong.
