### ISSUE TITLE
/myprofile lacks "name"

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse-api#296]
http://localhost:8000/api/pulse/myprofile/ currently has `custom_name`, but not `name`. Do we want to address that?

**Comment by xmatthewx** [comment]
From where I sit, we should just have profile.name, and stop calling it custom. When a profile is created, this field should default to user.name if it exists. If not, user or staff making a profile can input it. I'm not sure why the label "custom" was introduced. While we store user.name, that only serves admin purposes for account issues and isn't used otherwise by the platform.

**Comment by Pomax** [comment]
Closing this issue due to having gone stale - if this is still something we want to do, let's file a new issue with all the information necessary for triaging.
