### ISSUE TITLE
Interactive mode for the fake data factories

### ISSUE THREAD

**Issue by patjouk** [mozilla/network-pulse-api#344]
`load-fake-data` create a fixed number of fake creators, entries, fellows, etc. We might want to create a different mode that would let people enter the number of elements they want. Of course, we will keep an automatic mode for the review apps.

We could use [click-cli](http://click.pocoo.org/5/) and [django click](https://pypi.python.org/pypi/django-click/2.0.0).

@gideonthomas

**Comment by gideonthomas** [comment]
`django-click` looks pretty promising. I can envision a tool that would ask you for which models you want to configure the amount of instances generated and then ask how many instances for each you want generated (for relationships as well). Another nice addition could be to save this configuration of how many instances are generated in a gitignored file so that it can be auto-loaded later on.

**Comment by patjouk** [comment]
Hi Gideon :) Just to check before I start working on that: is it still something that would help you?

**Comment by gideonthomas** [comment]
Yep! I think it'll help so that I don't have to use prod data anymore :)

**Comment by patjouk** [comment]
I see :D I'll start working on it then!
