### ISSUE TITLE
Add Github OAuth support

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#410]
Using the existing library, let's add support for authentication with Github.

@gideonthomas does this require anything from design to choose which login type to use for OAuth?

**Comment by gideonthomas** [comment]
We can change designs later. I already designed something for now. There will be some front-end follow-up work that needs to be done though -- to change routes used.

**Comment by xmatthewx** [comment]
How's this going @gideonthomas @alanmoo ? What do you think our timeline looks like for wrapping up https://github.com/mozilla/network-pulse-api/pull/413?

**Comment by gideonthomas** [comment]
should land next week. then we need to test this for at least a week and make sure there aren't any issues.

**Comment by xmatthewx** [comment]
Okay. Let's check in with @acabunoc when it's ready to test.

**Comment by Pomax** [comment]
It looks like we have an artificial "are you real?" confirmation step at the moment, where users can log in with github, allow the link permissions on the GH side (Which they can only do when logged into github, which for staff means they're already 2FA-logged in, too), but are then asked to first confirm this by email as well, instead of skipping the email verification step.

We can trust github to provide correect information there, so it might be worth looking at the lib we're using to find out how we can turn off that extra step. Once a user gives permission on the github side, they should be allowed in without additional verification.

**Comment by alanmoo** [comment]
Seems like this can be closed as #415 is the followup. Correct me if I'm wrong.
