### ISSUE TITLE
Update docs with correct payload for profiles

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse-api#484]
All users should be able to update their location via the front-end client. It looks like this requires enabling them to POST to the backend.

**Comment by gideonthomas** [comment]
This is already possible using PUT - https://github.com/mozilla/network-pulse-api#put-apipulsemyprofile

The documentation for the route is incorrect though since the payload accepts pretty much everything [in here](https://github.com/mozilla/network-pulse-api#profile-object-schema) that is editable

**Comment by alanmoo** [comment]
Cool. Can you update the documentation to close this ticket?
