### ISSUE TITLE
Forced SSL redirect on test.example.com?

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-pulse-api#73]
I can't figure out how to turn off forced SSL when in development. 

OS: Ubuntu 16.10
Python: 3.5

I ran:
1. `pip install -r requirements.txt`
2. `python manage.py migrate`
3. `cp sample.env .env`
4. `python manage.py runserver`

Trying to access the admin page results in a redirect to https://test.example.com, which is rejected by the dev server.

**Comment by Pomax** [comment]
How did you tell the API server which Google authentication endpoint to use? (And did you make sure to make that endpoint use `http://test.example.com` for its callback URL?)

Alternatively this might be caused by something in https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/settings.py#L175 with a fallback to https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/settings.py#L26... but it sounds like a it might also be google auth directing to the wrong URL

**Comment by Pomax** [comment]
gauth updates made example.com unnecessary
